### ISSUE TITLE
Próximos passos

### ISSUE THREAD

**Issue by Nakamurayamato** [kaiba-corp/dafiti-selenium#1]
- [x] If produto_esgotado : continue
- [x] Exportar os resultados em uma planilha

@matheuspsilva1

**Comment by matheuspsilva1** [comment]
boa

**Comment by Nakamurayamato** [comment]
Não teve nenhum pull requests, nem um avanço aqui?

**Comment by LordLole** [comment]
ainda to busca do que é SKU's

**Comment by matheuspsilva1** [comment]
eu to na busca de como que faz um pull requests

**Comment by LordLole** [comment]
Feito
